{% set name = "reports" %}
{% set version = "0.4.1" %}
{% set sha256 = "2221c1f5c268b56d1d862189319cdc6fd84a3041a29edd51ab5aa71c9354edae" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: reports-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools
    - easydev
    - pandas
    - colormap
    - jinja2


test:
  imports:
    - reports
    - reports.resources

about:
  home: http://github.com/cokelaer/reports/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  doc_url: http://reports.readthedocs.io/en/latest
  dev_url: https://github.com/cokelaer/reports

  summary: Quickly create HTML reports using a set of JINJA templates

extra:
  recipe-maintainers:
    - cokelaer
