travis:
  secure:
    BINSTAR_TOKEN: Xook3gh0KXPOI9SbztGaWxNgn89vuzwWZ5Z0SF7OgW8dggg0DqKzIMAtj3PU1WiLzNp6aOxXDnW9EtfCxEDmWgCELWKExzQRa602BXxfeTSq7lyzAZQTBMMao+PdvinPsSN2LUmLHKhvbKqArKw9F53B1IHpXlY2zg9hCN2qg2Dp8x4FGM3bczaW92XaxjP63r9sTpTiX4vc5D1FFRP2a+R69DgPe+wQknBtNwi2tKfb0i89bY/xfqXPYKlTgW5Jsdhb9kr8PMnYYgXL2l0ux7ZiLQoZgrK8+N/Qgq1ey+sj9MPYXQRQgHCOltOAkcwCA8ZY5q8KqUEmIRyARH516fN69q+Bi0xrtxBxDLhPOp4HFTI0l0ON7p762AtpIQBglER0W583Z98I2jKj46niPVConPiYE/0V/b4sZiRbJLMgWylJbaU6oz6dxaYOqLu2d7Ji8qDQ8JyRXo2rO1Ls/e1mQuKA6GDsJ+H+oiQHxKfk/irbxJWGfzpjNV9Ey3Kc15d7pJmXOTMhPn6SxSaUwaStVyTvOkPlWjICNJEvLvGd0/WlU/RXWlm6aayy20vvntdKaDxgG+IVtg3MQHdzD6LTqW0HI9p2IEacsA+qAiIgKd1rLqI5OXmfWOz9y0dqXvr3o0PcafW4ST002+ORj50dImPARcpArVw92AycezI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
