travis:
  secure:
    BINSTAR_TOKEN: fcMAp+phr31scPxSUkOfwjkQRSVP5n6qS12scDEHWGeX//cT5HJ6KIgysWKDG3aii+OOqmAer1xU+IA2FYRHlNopprD9UzOb0hfRuW/yVCN9Y/v77YyS++Z5Kiy3Ht9O7rlCo7fKKBE6qPoct9dsMt41uvcs2uotgdHn+/NC91bxXVZVPrloiCWaHFy+0Hp9df2MqAW4GW3ZkbBKrmrAMpsTQMaOmVNb/c28xVHAneyDrUdLLuQpM7fDTxCNfMAvgdIKPFcXotay4/Pf9EF6diIh4opp878DxjUdqcmlPJ4U+aE/Rl5I9rA4JG8PENx83EoUrJND0ZMN6RF4EHuloThcRS9A7K374kQqf9WEA9Sqcb/GP+8+XMzTipU2ryCV8pFKRRCn8UvzEWRLs4x4JxiQ1UQMaKx1qBOQEa4aSlrujC+QGDUxyvL+ueXyJ8/NEs+vtaDC0I6j/Z8tA0twWqp+lv8gYf2cZmm5M0+oCgd41tK2l77UIsY/pOqWxywRpithU3Rh+8zaS60bEjaEqIhQSdkJqByghIlDpdF1cogBnEBjbPyM5973/t48xxBALAzhcEC6wgNq7k7fOeU/83jpPQUoW4xjUzQNN5xsCVvGNmT/g3n3hnEP9KfpjHfF7xqX3vqUADiMCNTgv9IpDKhtZSO1L8s1RQoXyS9Hz/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
